"""message

Revision ID: 224b8ff21f98
Revises: fdb65ec8fc0c
Create Date: 2024-07-06 13:16:11.411609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224b8ff21f98'
down_revision = 'fdb65ec8fc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
